# Generated by Django 5.1.1 on 2024-09-09 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('is_gallery', models.BooleanField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('large_url', models.URLField()),
                ('medium_url', models.URLField()),
                ('small_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating_average', models.DecimalField(decimal_places=2, max_digits=3)),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('quantity_sold', models.CharField(max_length=255)),
                ('publisher_vn', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('dimensions', models.TextField(blank=True, null=True)),
                ('dich_gia', models.TextField(blank=True, null=True)),
                ('number_of_page', models.CharField(max_length=255)),
                ('is_hidden', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('images', models.ManyToManyField(to='api.image')),
                ('current_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
            ],
        ),
    ]
