# Generated by Django 5.1.1 on 2024-09-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity_sold',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
