# Generated by Django 5.1.1 on 2024-09-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_manufacturer_alter_book_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='list_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_price',
            field=models.IntegerField(),
        ),
    ]
