# Generated by Django 5.1.1 on 2024-09-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loai_bia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
