# Generated by Django 5.1.1 on 2024-09-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_loai_bia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity_sold',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
