# Generated by Django 5.1.1 on 2024-09-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_book_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
