# Generated by Django 5.1.1 on 2024-09-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_book_percent_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity_sold',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
