# Generated by Django 5.1.1 on 2024-09-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_book_percent_alter_book_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
