# Generated by Django 5.1.1 on 2024-09-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_book_number_of_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_gallery',
            field=models.BooleanField(default=True),
        ),
    ]
