# Generated by Django 5.1.1 on 2024-09-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_image_is_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
